import 'package:flutter/cupertino.dart';

import 'package:google_fonts/google_fonts.dart';

class GetTextTheme {
  //Bold Text
  static TextStyle fs55_tin =
      GoogleFonts.poppins(fontSize: 50, fontWeight: FontWeight.w100);
  static TextStyle fs40_tin =
      GoogleFonts.poppins(fontSize: 30, fontWeight: FontWeight.w100);
  static TextStyle fs48_bold =
      GoogleFonts.poppins(fontSize: 40, fontWeight: FontWeight.w700);
  static TextStyle fs40_bold =
      GoogleFonts.poppins(fontSize: 40, fontWeight: FontWeight.w700);
  static TextStyle fs35_bold =
      GoogleFonts.poppins(fontSize: 35, fontWeight: FontWeight.w700);
  static TextStyle fs32_bold =
      GoogleFonts.poppins(fontSize: 32, fontWeight: FontWeight.w700);
  static TextStyle fs30_bold =
      GoogleFonts.poppins(fontSize: 30, fontWeight: FontWeight.w700);
  static TextStyle fs28_bold =
      GoogleFonts.poppins(fontSize: 28, fontWeight: FontWeight.w700);
  static TextStyle fs26_bold =
      GoogleFonts.poppins(fontSize: 26, fontWeight: FontWeight.w700);
  static TextStyle fs24_bold =
      GoogleFonts.poppins(fontSize: 24, fontWeight: FontWeight.w700);
  static TextStyle fs22_bold =
      GoogleFonts.poppins(fontSize: 22, fontWeight: FontWeight.w700);
  static TextStyle fs20_bold =
      GoogleFonts.poppins(fontSize: 20, fontWeight: FontWeight.w700);
  static TextStyle fs18_bold =
      GoogleFonts.poppins(fontSize: 18, fontWeight: FontWeight.w700);
  static TextStyle fs16_bold =
      GoogleFonts.poppins(fontSize: 16, fontWeight: FontWeight.w700);
  static TextStyle fs14_bold =
      GoogleFonts.poppins(fontSize: 14, fontWeight: FontWeight.w700);
  static TextStyle fs12_bold =
      GoogleFonts.poppins(fontSize: 12, fontWeight: FontWeight.w700);
  static TextStyle fs10_bold =
      GoogleFonts.poppins(fontSize: 10, fontWeight: FontWeight.w700);

  //Medium Text

  static TextStyle fs48_medium =
      GoogleFonts.poppins(fontSize: 40, fontWeight: FontWeight.w600);
  static TextStyle fs40_medium =
      GoogleFonts.poppins(fontSize: 40, fontWeight: FontWeight.w600);
  static TextStyle fs35_medium =
      GoogleFonts.poppins(fontSize: 35, fontWeight: FontWeight.w600);
  static TextStyle fs32_medium =
      GoogleFonts.poppins(fontSize: 32, fontWeight: FontWeight.w600);
  static TextStyle fs30_medium =
      GoogleFonts.poppins(fontSize: 30, fontWeight: FontWeight.w600);
  static TextStyle fs28_medium =
      GoogleFonts.poppins(fontSize: 28, fontWeight: FontWeight.w600);
  static TextStyle fs26_medium =
      GoogleFonts.poppins(fontSize: 26, fontWeight: FontWeight.w600);
  static TextStyle fs24_medium =
      GoogleFonts.poppins(fontSize: 24, fontWeight: FontWeight.w600);
  static TextStyle fs22_medium =
      GoogleFonts.poppins(fontSize: 22, fontWeight: FontWeight.w600);
  static TextStyle fs20_medium =
      GoogleFonts.poppins(fontSize: 20, fontWeight: FontWeight.w600);
  static TextStyle fs18_medium =
      GoogleFonts.poppins(fontSize: 18, fontWeight: FontWeight.w600);
  static TextStyle fs16_medium =
      GoogleFonts.poppins(fontSize: 16, fontWeight: FontWeight.w600);
  static TextStyle fs14_medium =
      GoogleFonts.poppins(fontSize: 14, fontWeight: FontWeight.w600);
  static TextStyle fs12_medium =
      GoogleFonts.poppins(fontSize: 12, fontWeight: FontWeight.w600);
  static TextStyle fs10_medium =
      GoogleFonts.poppins(fontSize: 10, fontWeight: FontWeight.w600);

  //Regular Text
  static TextStyle fs48_regular =
      GoogleFonts.poppins(fontSize: 40, fontWeight: FontWeight.w400);
  static TextStyle fs40_regular =
      GoogleFonts.poppins(fontSize: 40, fontWeight: FontWeight.w400);
  static TextStyle fs35_regular =
      GoogleFonts.poppins(fontSize: 35, fontWeight: FontWeight.w400);
  static TextStyle fs32_regular =
      GoogleFonts.poppins(fontSize: 32, fontWeight: FontWeight.w400);
  static TextStyle fs30_regular =
      GoogleFonts.poppins(fontSize: 30, fontWeight: FontWeight.w400);
  static TextStyle fs28_regular =
      GoogleFonts.poppins(fontSize: 28, fontWeight: FontWeight.w400);
  static TextStyle fs26_regular =
      GoogleFonts.poppins(fontSize: 26, fontWeight: FontWeight.w400);
  static TextStyle fs24_regular =
      GoogleFonts.poppins(fontSize: 24, fontWeight: FontWeight.w400);
  static TextStyle fs22_regular =
      GoogleFonts.poppins(fontSize: 22, fontWeight: FontWeight.w400);
  static TextStyle fs20_regular =
      GoogleFonts.poppins(fontSize: 20, fontWeight: FontWeight.w400);
  static TextStyle fs18_regular =
      GoogleFonts.poppins(fontSize: 18, fontWeight: FontWeight.w400);
  static TextStyle fs16_regular =
      GoogleFonts.poppins(fontSize: 16, fontWeight: FontWeight.w400);
  static TextStyle fs14_regular =
      GoogleFonts.poppins(fontSize: 14, fontWeight: FontWeight.w400);
  static TextStyle fs13_regular =
      GoogleFonts.poppins(fontSize: 13, fontWeight: FontWeight.w400);
  static TextStyle fs12_regular =
      GoogleFonts.poppins(fontSize: 12, fontWeight: FontWeight.w400);
  static TextStyle fs10_regular =
      GoogleFonts.poppins(fontSize: 10, fontWeight: FontWeight.w400);

  static TextStyle fs55_extrabold =
      GoogleFonts.poppins(fontSize: 55, fontWeight: FontWeight.w800);
  static TextStyle fs28_extrabold =
      GoogleFonts.poppins(fontSize: 28, fontWeight: FontWeight.w800);
  static TextStyle fs25_extrabold =
      GoogleFonts.poppins(fontSize: 25, fontWeight: FontWeight.w800);
  static TextStyle fs24_extrabold =
      GoogleFonts.poppins(fontSize: 24, fontWeight: FontWeight.w800);
  static TextStyle fs23_extrabold =
      GoogleFonts.poppins(fontSize: 23, fontWeight: FontWeight.w800);
  static TextStyle fs22_extrabold =
      GoogleFonts.poppins(fontSize: 22, fontWeight: FontWeight.w800);
  static TextStyle fs21_extrabold =
      GoogleFonts.poppins(fontSize: 21, fontWeight: FontWeight.w800);
  static TextStyle fs20_extrabold =
      GoogleFonts.poppins(fontSize: 20, fontWeight: FontWeight.w800);
  static TextStyle fs19_extrabold =
      GoogleFonts.poppins(fontSize: 19, fontWeight: FontWeight.w800);
  static TextStyle fs18_extrabold =
      GoogleFonts.poppins(fontSize: 18, fontWeight: FontWeight.w800);
  static TextStyle fs17_extrabold =
      GoogleFonts.poppins(fontSize: 17, fontWeight: FontWeight.w800);
  static TextStyle fs16_extrabold =
      GoogleFonts.poppins(fontSize: 16, fontWeight: FontWeight.w800);
  static TextStyle fs15_extrabold =
      GoogleFonts.poppins(fontSize: 15, fontWeight: FontWeight.w800);
  static TextStyle fs14_extrabold =
      GoogleFonts.poppins(fontSize: 14, fontWeight: FontWeight.w800);
  static TextStyle fs13_extrabold =
      GoogleFonts.poppins(fontSize: 13, fontWeight: FontWeight.w800);
  static TextStyle fs12_extrabold =
      GoogleFonts.poppins(fontSize: 12, fontWeight: FontWeight.w800);
  static TextStyle fs11_extrabold =
      GoogleFonts.poppins(fontSize: 11, fontWeight: FontWeight.w800);
  static TextStyle fs10_extrabold =
      GoogleFonts.poppins(fontSize: 10, fontWeight: FontWeight.w800);

  //........black//

  static TextStyle fs55_black =
      GoogleFonts.poppins(fontSize: 55, fontWeight: FontWeight.w900);
  static TextStyle fs28_black =
      GoogleFonts.poppins(fontSize: 28, fontWeight: FontWeight.w900);
  static TextStyle fs25_black =
      GoogleFonts.poppins(fontSize: 25, fontWeight: FontWeight.w900);
  static TextStyle fs24_black =
      GoogleFonts.poppins(fontSize: 24, fontWeight: FontWeight.w900);
  static TextStyle fs23_black =
      GoogleFonts.poppins(fontSize: 23, fontWeight: FontWeight.w900);
  static TextStyle fs22_black =
      GoogleFonts.poppins(fontSize: 22, fontWeight: FontWeight.w900);
  static TextStyle fs21_black =
      GoogleFonts.poppins(fontSize: 21, fontWeight: FontWeight.w900);
  static TextStyle fs20_black =
      GoogleFonts.poppins(fontSize: 20, fontWeight: FontWeight.w900);
  static TextStyle fs19_black =
      GoogleFonts.poppins(fontSize: 19, fontWeight: FontWeight.w900);
  static TextStyle fs18_black =
      GoogleFonts.poppins(fontSize: 18, fontWeight: FontWeight.w900);
  static TextStyle fs17_black =
      GoogleFonts.poppins(fontSize: 17, fontWeight: FontWeight.w900);
  static TextStyle fs16_black =
      GoogleFonts.poppins(fontSize: 16, fontWeight: FontWeight.w900);
  static TextStyle fs15_black =
      GoogleFonts.poppins(fontSize: 15, fontWeight: FontWeight.w900);
  static TextStyle fs14_black =
      GoogleFonts.poppins(fontSize: 14, fontWeight: FontWeight.w900);
  static TextStyle fs13_black =
      GoogleFonts.poppins(fontSize: 13, fontWeight: FontWeight.w900);
  static TextStyle fs12_black =
      GoogleFonts.poppins(fontSize: 12, fontWeight: FontWeight.w900);
  static TextStyle fs11_black =
      GoogleFonts.poppins(fontSize: 11, fontWeight: FontWeight.w900);
  static TextStyle fs10_black =
      GoogleFonts.poppins(fontSize: 10, fontWeight: FontWeight.w900);
}
